STOP_WORDS = {'be', 'he', 'same', 'before', 'we', 'was', 'as', 
            'out', 'hers', 'over', 'having', 'for', 'i', 'nor', 
            'on', 'very', 'himself', 'now', 'she', 'until', 'are', 
            'is', 'if', 'do', 'more', 'should', 'in', 'when', 
            'these', 'between', 'to', 'our', 'which', 'or', 'off', 
            'you', 'such', 'at', 'his', 'of', 'during', 'further', 
            'so', 'by', 'where', 'ours', 'theirs', 'few', 'some', 
            'a', 'about', 'yourselves', 'not', 'up', 'been', 'because',
             'how', 'themselves', 'her', 'and', 'being', 'then', 
             'did', 'why', 'all', 'both', 'but', 'itself', 'the', 
             'under', 'too', 'yours', 'its', 'have', 'most', 'above', 
             'down', 'only', 'my', 'from', 'me', 'this', 'here', 'whom', 
             'yourself', 'through', 'am', 'has', 'while', 'herself', 
             'other', 'them', 'what', 'just', 'there', 'than', 'can',
              'any', 'don', 'myself', 'that', 'no', 'who', 'each', 'will',
               'him', 'it', 'their', 'below', 'own', 'had', 'after', 
               'ourselves', 'into', 'doing', 'they', 'those', 'your',
                'against', 'again', 'with', 'once', 'were', 'does', 'an'}
